# 完整配置示例
# Complete Configuration Example
# 复制此文件并根据需要修改

[General]
AppName = "code-push-server"
Version = "v0.0.1"
Debug = false
DisableSwagger = true
DisablePrintConfig = false

[General.HTTP]
Addr = ":8040"
ShutdownTimeout = 10  # seconds
ReadTimeout = 60      # seconds
WriteTimeout = 60     # seconds
IdleTimeout = 10      # seconds
CertFile = ""         # HTTPS 证书文件路径
KeyFile = ""          # HTTPS 私钥文件路径

# 数据库配置
[Database]
Driver = "postgres"   # 支持: sqlite, postgres, mysql
DSN = "postgres://user:password@localhost:5432/codepush?sslmode=disable"
MaxOpenConns = 25
MaxIdleConns = 10
ConnMaxLifetime = 300  # seconds

# 数据库迁移配置
[Database.Migration]
AutoMigrate = true
MigrationPath = "migrations"
SeedData = false

# 数据库连接配置
[Database.Connection]
MaxRetries = 3
RetryInterval = 5  # seconds
PingTimeout = 10   # seconds

# 数据库日志配置
[Database.Logging]
LogLevel = "warn"
SlowQueryThreshold = 1000  # milliseconds
LogQueries = false

# 日志配置
[Log]
Level = "info"        # debug, info, warn, error
Format = "json"       # json, text
Output = "file"       # stdout, file
FilePath = "logs/app.log"
MaxSize = 100         # MB
MaxBackups = 7
MaxAge = 30           # days
Compress = true

# 缓存配置
[Cache]
Type = "redis"        # memory, redis
TTL = 3600           # seconds

# Redis 缓存配置
[Cache.Redis]
Addr = "localhost:6379"
Password = ""
DB = 0
PoolSize = 10

# 安全配置
[Security]
JWTSecret = "your-jwt-secret-key"
JWTExpiration = 86400  # seconds
EncryptionKey = "your-32-character-encryption-key"

# CORS 配置
[Security.CORS]
AllowedOrigins = ["*"]
AllowedMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
AllowedHeaders = ["*"]
ExposedHeaders = []
AllowCredentials = true
MaxAge = 86400  # seconds

# 限流配置
[Security.RateLimit]
Enable = true
RequestsPerMinute = 100
BurstSize = 20
CleanupInterval = 300  # seconds

# 认证配置
[Security.Auth]
TokenType = "Bearer"
TokenHeader = "Authorization"
RefreshTokenExpiration = 604800  # seconds (7 days)

# 密码策略配置
[Security.Password]
MinLength = 8
RequireUppercase = true
RequireLowercase = true
RequireNumbers = true
RequireSymbols = true
MaxAttempts = 5
LockoutDuration = 900  # seconds (15 minutes)

# 第三方服务配置
[Services]

# 邮件服务配置
[Services.Email]
Provider = "smtp"     # smtp, sendgrid, ses
Host = "smtp.gmail.com"
Port = 587
Username = "your-email@gmail.com"
Password = "your-app-password"
From = "noreply@yourdomain.com"

# 对象存储配置
[Services.Storage]
Provider = "s3"       # local, s3, oss
LocalPath = "storage" # 本地存储路径
Region = "us-west-2"  # AWS 区域
Bucket = "your-bucket-name"
AccessKey = "your-access-key"
SecretKey = "your-secret-key"

# 监控配置
[Monitoring]
EnableMetrics = true
MetricsAddr = ":9090"
EnableTracing = false
TracingEndpoint = "http://jaeger:14268/api/traces"

# 业务配置
[Business]
# 应用包配置
[Business.Package]
MaxSize = 104857600   # 100MB
AllowedTypes = ["ipa", "apk", "zip"]
StoragePath = "packages"

# 版本管理配置
[Business.Version]
MaxVersions = 100
AutoCleanup = true
CleanupInterval = 86400  # seconds (24 hours)

# 用户管理配置
[Business.User]
MaxUsers = 1000
DefaultRole = "developer"
SessionTimeout = 3600  # seconds 