root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# 使用delve调试器启动
args_bin = ["--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient", "exec", "./tmp/main-debug.exe", "--", "start", "-c", "configs", "-e", "dev"]
bin = "dlv"
# 编译时加入调试信息，禁用优化
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main-debug.exe ."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "logs"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "toml", "yaml", "yml"]
include_file = []
kill_delay = "2s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_root = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true 